### PR TITLE
Refactoring of baseline computation

### PR DESCRIPTION
**Pull request by dneise**
Work in progress.

I was looking at files in this folder to get a better overview of digicampipe. 
In the process I pep8-ed the files. 

I think `extract_baseline` is quite large and has complex expressions. I would like to understand these expressions better and write them in simpler forms down. So future readers can understand quicker.

In order to make sure I do not break this, while trying to improve readablility, I will implement a test first.
After all chances are high, that a person modifying code she does not understand, might break it.

So next: a test for `extract_baseline` then refactoing of that function

### CODE REVIEW

**Comment by calispac** [comment]
This is an ugly part of the code. Probably the ugliest ^^. We need to take care for this. 
Refactoring of the baseline computation would be one of the next tasks.

**Comment by dneise** [comment]
Okay .. started it .. but can you show me how to call this function? 
An example would be good. I do not know what the `calib_container` is

**Comment by dneise** [comment]
Ah .. you self assigned .. I didn't get that. 

Okay I'll do something else

**Comment by dneise** [comment]
@calispac do you still work on this? Or should I give it a shot?

**Comment by calispac** [comment]
No I haven't found time. But you can go on if you want... sorry.

**Comment by calispac** [comment]
Just to give an update: I was waiting for a Processor() interface to come to start with this. But we still have to decide on what to do and not to do. See #119 and #122 
I suppose we can go ahead with simple functions.

**Comment by dneise** [comment]
Nope

**Pull request closed without merging**
