### PR TITLE
using latest protozfitsreader version

### PR DESCRIPTION
**Pull request by calispac**
In this PR we try the latest version of the protozfitsreader.

https://github.com/cta-sst-1m/protozfitsreader/archive/1.0.0.tar.gz

### CODE REVIEW

**Comment by calispac** [comment]
ok this PR seems to pass the tests. But I doubt that in the newest version it will work it the files do not contain trigger input/output traces. @dneise I will try to fix that in the protozfitsreader

**Comment by calispac** [comment]
Do not merge yet ! this need cta-sst-1m/protozfitsreader/pull/34 to be merged

**Comment by dneise** [comment]
This seems to work for now ... So even if I rather would like to have it in a different way .. should we merge this today so you can work?

**Comment by dneise** [comment]
protozfits v1.0.1 was just relelased:

https://github.com/cta-sst-1m/protozfitsreader/archive/v1.0.1.tar.gz

It is not mentioned on the README yet ... but that's maybe okay.

**Comment by calispac** [comment]
ok thanks!

**Pull request merged**
