### PR TITLE
use protozfits with a hotfix

### PR DESCRIPTION
**Pull request by dneise**
In issue #212 Vasyl reportet a bug in the protozfits reader in case of missing baseline field.
In this PR I propose to use a version of the protozfits reader v1.0.1b0 which is hopefully fixing this issue.

If you have the current master of digicampipe installed and want to test this, you can do:

    pip uninstall protozfits --yes
    pip install https://github.com/cta-sst-1m/protozfitsreader/archive/v1.0.1b0.tar.gz

Maybe @vasylbeshley would like to test this ... and if it works could review this pull request, so we can merge this fix into the master.

### CODE REVIEW

**Comment by dneise** [comment]
Thank you Vasyl for testing this.

Could you present a bit more of the error message? There is usually one very interesting line directly above the line you cited... It says the filename and the line number where the error was caused. 

Alternatively maybe you could upload the file you are using here? That could be quite helpful to reproduce and finally solve this issue.

**Comment by vasylbeshley** [comment]
Yes, sorry I have provided you not full information. The full information you can see below.

(digicampipe) vasyl@debv:~$ digicam-view /home/vasyl/CTA/digicampipe/SST1M_01_0_000.006.fits.fz 
WARNING:matplotlib.legend:No handles with labels found to put in legend.
Events:   0%|                                         | 0/12701 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/bin/digicam-view", line 11, in <module>
    load_entry_point('digicampipe', 'console_scripts', 'digicam-view')()
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/scripts/digicamview.py", line 15, in entry
    display.draw()
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/visualization/__init__.py", line 205, in draw
    self.next()
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/visualization/__init__.py", line 148, in next
    for i, event in zip(range(step), self.event_stream):
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/io/event_stream.py", line 50, in event_stream
    for event in data_stream:
  File "/home/vasyl/astro_soft/ctasoft/digicampipe/digicampipe/io/zfits.py", line 90, in zfits_event_source
    desc='Events', leave=False):
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/protozfits/digicam.py", line 30, in __next__
    return Event(event, self.run_id)
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/protozfits/digicam.py", line 62, in __init__
    self.baseline = self.unsorted_baseline[Event._sort_ids]
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/astropy/utils/decorators.py", line 711, in __get__
    val = self.fget(obj)
  File "/home/vasyl/astro_soft/anaconda3_520/envs/digicampipe/lib/python3.5/site-packages/protozfits/digicam.py", line 113, in unsorted_baseline
    "of run_id:{1}".format(self.event_number, self.run_id)
AttributeError: 'Event' object has no attribute 'event_number'

You can find zfitsviewer image and fits.fz here (https://drive.google.com/drive/folders/1OZrPdRUCVfymqMGB20KWg0J6b9bNgAj5?usp=sharing)

**Comment by dneise** [comment]
Perfect! No need to say sorry :-D ... it is just the more information I have the quicker I might be able to help. 

So just to tell you, in this case all I needed was this:
```

**Comment by vasylbeshley** [comment]
Now, it works for me too. Thank you!

**Pull request merged**
