### PR TITLE
Move protozfitsreader to its own package

### PR DESCRIPTION
**Pull request by dneise**

### CODE REVIEW

**Comment by dneise** [comment]
This can only work when 
https://github.com/cta-sst-1m/protozfitsreader/pull/10
is merged and protozfitsreader v0.43.2 is released.

**Comment by dneise** [comment]
Okay so this is still waiting for this:
https://github.com/cta-sst-1m/protozfitsreader/pull/10

to be merged, which should only be a formality ...

**Comment by calispac** [comment]
what is the status here?

**Comment by dneise** [comment]
This was written against a hypothetical protozfitsreader release v.0.43.2 (which was never created). Instead the features we need here are in the freshly created release v0.44.1

So let me quickly change this...

**Comment by dneise** [comment]
Okay ... now it becomes interesting again .. tests are running ... but if they are passing, we will see. ...

**Comment by dneise** [comment]
This will also fix #94

**Comment by dneise** [comment]
Test are passing, I assume we can merge.

**Pull request merged**
